version: '{build}'
image: Ubuntu

branches:
  only:
    - master
    - develop

pull_requests:
  do_not_increment_build_number: true

build_script:
- ps: .\build.ps1

artifacts:
- path: '.\artifacts\*.nupkg'